### PR TITLE
Fixed a bug that the original view's alpha is 0 after transition.

### PR DESCRIPTION
**Pull request by CocoaBob**

### CODE REVIEW

**Comment by DenHeadless** [comment]
Can you explain a little bit more, where this bug is happening? Hiding view that we are transitioning from was the original idea, since we animate snapshot between two views, not the view itself.

**Comment by CocoaBob** [comment]
As what I understand, the `zoomFromView` & `zoomToView` are the views from the protocol, which probably is a table view cell or a collection view cell.

Yes, you are right, we need `zoomToView` becomes transparent during the transition animation.

But after pushing a VC, when the animation is completed, if we still keep the `zoomFromView.alpha = 0`, the cell from the 1st VC will be transparent, its snapshot will be transparent too.

If we tap Back button to trigger the back transition, in the method `-initialZoomSnapshotFromView:destinationView:`,  if `fromSnapshot.size.width <= toSnapshot.size.width`, we will choose the snapshot of the original `zoomFromView`, which is now the `zoomToView`, and it's transparent because `alpha = 0` in the last animation.

So the `animateSnapshot` is transparent, the `animatingImageView` is transparent too. The result is that, the Back transition is invisible.

To correct the problem, we just need to reset the alpha values to 1 in the completion block. As the animation has already finished, the 1st view is covered by the 2nd view, users can't see the change.

In your example, the 1st image view is always smaller than the 2nd one, so the bug doesn't appear. Try to make the 1st one larger than the 2nd one, then you will find it.

Anyway, your solution is much more graceful than the others, thank you very much!

**Comment by DenHeadless** [comment]
Thanks! 

I've released 0.2.4 version with this fix :beer:

**Comment by CocoaBob** [comment]
Actually I'm looking for a solution to return nil in the method `-navigationController:animationControllerForOperation:toViewController:` when it's necessary to not use this zoom transition. For example, zoom transit from VC1 to VC2, but normal push animation from VC2 to VC3.
I think we can return nil in the protocol method, but the problem is that this navigation delegate method is called before `-viewDidLoad` of the destination VC, when the view which is going to be returned hasn't been ready yet.

**Comment by DenHeadless** [comment]
Sorry, can't help you with that =) This library is more like a demonstration and is not being actively developed right now.

**Pull request merged**
